### ISSUE TITLE
Sample images with tile level QCD and QCC markers ?

### ISSUE THREAD

**Issue by boxerab** [openpreserve/jpylyzer#109]
Not an issue, but I"m looking for test images with tile-level QCD/QCC

Thanks!!

**Comment by bitsgalore** [comment]
Hi Aaron,

Don't know if this helps, but the [jpylyzer-test-files repo](https://github.com/openpreserve/jpylyzer-test-files) contains one sample image ("openJPEG15.jp2") that has a QCC marker. I don't have any images with a QCD marker though.

Cheers,

Johan

**Comment by boxerab** [comment]
Thanks, Johan ! Actually, I just found some images in my test set that have these markers.
Cheers,
Aaron
