### ISSUE TITLE
Add a public static code analysis and reporting for QAing pull requests

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jpylyzer#112]
## Dev Effort
1d

## Description
Check competeing solutions for static analysis of Python projects, e.g [Codacy](https://www.codacy.com/) or [LGTM](https://lgtm.com/) (thanks @stweil ). We should bear in mind that the chosen solution should support PEP (see issue #68 ) and pylint (see issue #91 ) or we provide justification as to our chosen approach. This task will be taken in as part of the continuous integration work.

**Comment by stweil** [comment]
https://lgtm.com/projects/g/openpreserve/jpylyzer/ already exists and does a nice job.

**Comment by carlwilson** [comment]
Will check this out and compare and contrast with Codacy. I've got no favourite in principal but already use Codacy for Java projects and favour fewer platforms. That said LGTM does look slick and if it's a better solution I'll use it.

**Comment by carlwilson** [comment]
This PR: #141 added various features including test coverage for Codacy. Can be considered closed when v2 release is merged to master.
