### ISSUE TITLE
Twine ignores long_description_content_type in setup.py 

### ISSUE THREAD

**Issue by bitsgalore** [openpreserve/jpylyzer#152]
Trying to make the PyPi packages by running:

    sudo ./package-pypi.sh

Result:

```
HTTPError: 400 Client Error: The description failed to render in the default format of
reStructuredText. See https://pypi.org/help/#description-content-type for more information.
for url: https://upload.pypi.org/legacy/
```
This indicates a problem with *long_description* in setup.py. So following the info in that link (<https://pypi.org/help/#description-content-type>), installed the [readme_renderer](https://pypi.org/project/readme_renderer/), the latest twine version, and then:

1. build the package:

    sudo python setup.py bdist_wheel --universal

2. test it:

     ~/.local/bin/twine check dist/*

Result:

```
Warning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Checking dist/jpylyzer-2.0.0rc1-py2.py3-none-any.whl: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 58: Warning: Inline emphasis start-string without end-string.
  warning: `long_description_content_type` missing.  defaulting to `text/x-rst`
```
So even though *long_description_content_type* in setup.py is set to 'text/markdown', for some reason twine does not understand this, assumes restructured text (which it uses as a default) and then rejects the upload.

**Comment by carlwilson** [comment]
@bitsgalore  it's the twine version: https://github.com/pypa/twine/issues/454

**Comment by carlwilson** [comment]
@bitsgalore I'd thought about suggesting that....

**Comment by bitsgalore** [comment]
Closing because Dockerizing fixes this.
