### ISSUE TITLE
"TypeError: expected string or bytes-like object" after running package-pypi.sh

### ISSUE THREAD

**Issue by bitsgalore** [openpreserve/jpylyzer#153]
Run packaging script:

```
sudo ./package-pypi.sh
```
Result: 

```
running sdist
running egg_info
::
:: etc.
:: 
Uploading distributions to https://test.pypi.org/legacy/
Uploading jpylyzer-2.0.0rc1-py2.py3-none-any.whl
TypeError: expected string or bytes-like object
```
The package does get uploaded, but the error should not happen (and did not happen earlier).

twine version 1.15.0 (pkginfo: 1.5.0.1, requests: 2.22.0, setuptools: 41.6.0,
requests-toolbelt: 0.9.1, tqdm: 4.36.1)

This looks like the following Twine issue:

<https://github.com/pypa/twine/issues/342>

**Comment by carlwilson** [comment]
Hi @bitsgalore this feels like it's another side of #152 and it might be fixed best by using a Dockerised stack that packs a consistent set of `setuptools` and associated. I suspect that the package is fine, markdown long description and all. We can look to fix these before the v2 release.

**Comment by bitsgalore** [comment]
@carlwilson Yep, was thinking that as well.

**Comment by bitsgalore** [comment]
Closing because Dockerizing fixes this.
