### ISSUE TITLE
Add documentation +  update XSD schema for PLM, PLT marker output

### ISSUE THREAD

**Issue by bitsgalore** [openpreserve/jpylyzer#174]
As per <https://github.com/openpreserve/jpylyzer/pull/170> (merged into 2.1 dev).

While at it, also have a look at <https://github.com/openpreserve/jpylyzer-test-files/issues/5>, which is related.

**Comment by VirtualTim** [comment]
I have a bunch of datasets with PLT markers, but I don't think I have any with PLM.
I'm happy to send you something with PLT if you want?

**Comment by bitsgalore** [comment]
We already have a couple of images with plt markers, but since you offered to provide some Hexagon JP2s [here](https://github.com/openpreserve/jpylyzer-test-files/issues/6) perhaps you could include an image with plt markers?

**Comment by bitsgalore** [comment]
Docs + schema done:

<https://github.com/openpreserve/jpylyzer/commit/8cee08b0cc995ce79f813e634909cbbba17d4617>
