### ISSUE TITLE
jpylyzer failing on compressed CMYK file with valid enumcs value of 12

### ISSUE THREAD

**Issue by boxerab** [openpreserve/jpylyzer#186]
[cmyk_no_wavelet.zip](https://github.com/openpreserve/jpylyzer/files/8492978/cmyk_no_wavelet.zip)

```
    <isValid format="jp2">False</isValid>
    <tests>
        <jp2HeaderBox>
            <colourSpecificationBox>
                <enumCSIsValid>False</enumCSIsValid>
            </colourSpecificationBox>
        </jp2HeaderBox>
```

**Comment by bitsgalore** [comment]
According to Table I.10 in [I15444-1:2004(E)](https://wiki.opf-labs.org/download/attachments/11337762/15444-1annexi.pdf), only 16, 17, and 18 are legal EnumCS values in JP2. So unless this has changed in some amendment to the standard that I'm unaware of (in which case please let me know), jpylyzer's behavior here looks correct to me.

**Comment by boxerab** [comment]
ahhh, right you are. This is a Part II enumcs.
