### ISSUE TITLE
2.1.0 Launching jpylyzer result in  Attempted relative import in non-package

### ISSUE THREAD

**Issue by TechiesOfficial** [openpreserve/jpylyzer#194]
Hello, working for BnF, we try to update to the last jyplyzer version (2.1) using python 2.7 before migrating to 3.2.

I've seen package import definition have changed between 2.0 and 2.1 and launching jpylyzer results in: 

`python jpylyzer.py
Traceback (most recent call last):
  File "jpylyzer.py", line 45, in <module>
    from . import config
ValueError: Attempted relative import in non-package`

I am not really familiar with python package definition but everything seems correct. There is a __init__.py file as can be seen:
`boxvalidator.py  byteconv.py  config.py  etpatch.py  __init__.py  jpylyzer.py  jpylyzer$py.class  __main__.py  mix.py  shared.py`

I tried with a python3.6 executable that was already available on the server but same result.

Thanks.

**Comment by bitsgalore** [comment]
Side note - you mention upgrading to Python 3.2. Not sure if that's a typo, but I would strongly recommend to upgrade to a more recent (3.8 or higher) version, because Python 3.2 was retired in early 2016, see overview here:

<https://devguide.python.org/versions/>

**Comment by TechiesOfficial** [comment]
We use jython nowaday and my manager came back from vacation and created a specific package.

We will throw away jython in our next updates.

There is nothing wrong on your side.

Thank you for your time.
