### ISSUE TITLE
Question about new PLM marker support

### ISSUE THREAD

**Issue by boxerab** [openpreserve/jpylyzer#228]
Hello! This is not specific to jpylyzer, but have you ever encountered an image with PLM markers in the wild ?
I have never seen one, as it seems everyone uses PLT markers, but I am curious about if PLM was ever used.
Thanks!

**Comment by boxerab** [comment]
ahhh, I see I asked this same question 3 years ago :)

**Comment by bitsgalore** [comment]
@boxerab Actually there's a file with a PLM marker in the Jpylyzer test files repo:

<https://github.com/openpreserve/jpylyzer-test-files/blob/master/files/oj-plm-main-header.jp2>

If you run jpylyzer on it with the `--packetmarkers` option you'll see this:

```xml
            <plm>
                <lplm>12</lplm>
                <zplm>0</zplm>
                <nplm>0</nplm>
                <iplm>00,01,00,05,04,04,00,00</iplm>
            </plm>
```

**Comment by boxerab** [comment]
@bitsgalore thanks! I will take a look at that one.
