### ISSUE TITLE
Issue running 1.6.0 against complex file name

### ISSUE THREAD

**Issue by jack-os** [openpreserve/jpylyzer#30]
I have three jp2 images which are named:

"x-fmt-392 (JPEG2000) [1].jp2"
"x-fmt-392 (JPEG2000) [2].jp2"
"x-fmt-392 (JPEG2000) [3].jp2"

When running any of the commands:

jpylyzer 'x-fmt-392 (JPEG2000) [1].jp2'
jpylyzer "x-fmt-392 (JPEG2000) [1].jp2"
jpylyzer x-fmt-392\ \(JPEG2000\)\ \[1\].jp2

the output is:
"User warning: no images to check!"

Similarly, running:

jpylyzer *.jp2

produces:
jpylyzer: error: unrecognized arguments: x-fmt-392 (JPEG2000) [2].jp2 x-fmt-392 (JPEG2000) [3].jp2

Running either of

jpylyzer '*.jp2'
jpylyzer "*.jp2"

results in the correct running of the program. Likewise if I rename one of the files "test.jp2", I am able to run the program on that file on its own.

**Comment by bitsgalore** [comment]
Issue cannot be reproduced with latest (1.16.0) release of jpylyzer (tried both Linux/ Windows), so earlier changes must have fixed this.

Looking at my Feb 12 2013 comment, I changed the filename/path encoding from iso-8859-15 (latin) to UTF-8, which should also ensure support of non-Western characters. Patch in commit:  

<https://github.com/openpreserve/jpylyzer/commit/c3034957b0da021fd40ef1d65e034d3c6d3c8c1e>
