### ISSUE TITLE
Website: Resources not loaded over HTTPS

### ISSUE THREAD

**Issue by mksplg** [openpreserve/jpylyzer#52]
## Dev Effort
0.5D

## Description
When opening the [Jpylyzer Website](https://openplanets.github.io/jpylyzer/) over HTTPS, CSS is blocked by modern browsers to avoid loading it over an unsecure connection. Images included via HTTP are loaded but show a warning in the browser's console.

To avoid this you could:
1. link all resources via their HTTPS links which works when opening the page over HTTP and HTTPS
2. use relative links

**Comment by bitsgalore** [comment]
**UPDATE**:  [this article describes how to use HTTPS with GitHub Pages + Custom Domains](https://jenmyers.net/using-https-with-github-pages-and-custom-domains.html).

**Comment by bitsgalore** [comment]
Working now after <https://github.com/openpreserve/jpylyzer/commit/d9d767fddbfa2e966451582e4dc5caacf4df4ea9>!
