### ISSUE TITLE
Create maintainer e-mail address at  jpylyzer-dev@openpreservation.org

### ISSUE THREAD

**Issue by bitsgalore** [openpreserve/jpylyzer#64]
## Dev Effort
0.5D

## Description
Debian control file mentions _jpylyzer-dev@openplanetsfoundation.org_. One would expect _jpylyzer-dev@openpreservation.org_ to work also, but that address does not exist.

**Comment by bitsgalore** [comment]
Update: old address is noty working anymore either (tried 17 Aug 2017).

**Comment by carlwilson** [comment]
Hi, @bitsgalore If you have received a test message for this address could you please let me know and we can close this.

**Comment by bitsgalore** [comment]
Yes, I received it! I'll close this issue now.

**Comment by bitsgalore** [comment]
I'm reopening this, because your test message used the old address (jpylyzer-dev@openplanetsfoundation.org). I just sent a test message to the new address (jpylyzer-dev@openpreservation.org), which bounced with the following error:

 
> This is a message delivery failure report.
> 
> Your message, received on Wednesday April 29, 2020 12:20:58 +0200 (CEST) from "[IPv6:2001:983:a12:1:c54:7a3f:7d60:ccda]" [2001:983:a12:1:c54:7a3f:7d60:ccda] could not be delivered to one or more recipients.
> 
> The following recipients did not receive the message:
> 
>   * jpylyzer-dev@openpreservation.org
> 
> The message could not be delivered, the mail server at aspmx.l.google.com [108.177.126.26] said:
> 
> <<< 550-5.1.1 The email account that you tried to reach does not exist. Please try 550-5.1.1 double-checking the recipient's email address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1 https://support.google.com/mail/?p=NoSuchUser l12si3066112edn.565 - gsmtp

**Comment by carlwilson** [comment]
OK, the list settings were to openplanetsfoundation.org and there's no rewrite from openpreservation.org -> openplanets... obviously. I updated this and it now seems to all work :)

**Comment by bitsgalore** [comment]
@carlwilson yes, working now, I'll close the issue again. Thanks!
