### ISSUE TITLE
Build errors on Travis

### ISSUE THREAD

**Issue by bitsgalore** [openpreserve/jpylyzer#65]
Lately jpylyzer's been giving build errors on Travis, e.g.:

<https://travis-ci.org/openpreserve/jpylyzer/jobs/55814485>

The error occurs right at the end of the process:

    dpkg-buildpackage: full upload; Debian-native package (full source is included)

    dpkg-buildpackage: warning: Failed to sign .dsc and .changes file

    The command "dpkg-buildpackage -tc" failed and exited with 1 during .

The output doesn't provide any more detailed clue as to what goes wrong exactly. The packages build normally on a local VM.

I'm wondering if this may have anything to do with the Travis config (also the error appears to have started after the transition of OPF to Open Preserervation Foundation, but that might just be a coincidence).

**Comment by carlwilson** [comment]
Hi Johan,

I noticed this myself the other evening. Am curious enough to have a look
at it, it wasn't clear to me that it wasn't something to do with fake root.

I'm busy with a couple of other issues but I'll start replaying some builds
and see what happens.

Best,
Carl

On 26 March 2015 at 12:31, Johan van der Knijff <notifications@github.com>
wrote:

> Lately jpylyzer's been giving build errors on Travis, e.g.:
>
> https://travis-ci.org/openpreserve/jpylyzer/jobs/55814485
>
> The error occurs right at the end of the process:
>
> dpkg-buildpackage: full upload; Debian-native package (full source is included)
>
> dpkg-buildpackage: warning: Failed to sign .dsc and .changes file
>
> The command "dpkg-buildpackage -tc" failed and exited with 1 during .
>
> The output doesn't provide any more detailed clue as to what goes wrong
> exactly. The packages build normally on a local VM.
>
> I'm wondering if this may have anything to do with the Travis config (also
> the error appears to have started after the transition of OPF to Open
> Preserervation Foundation, but that might just be a coincidence).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openpreserve/jpylyzer/issues/65>.
>



-- 
Carl Wilson | Technical Lead
carl@openpreservation.org | skype: carl.f.wilson
Open Preservation Foundation | www.openpreservation.org

**Comment by bitsgalore** [comment]
Ha, I see I could have saved myself writing that mail if I had only checked my inbox! Anyway, thanks for looking into to that!

Cheers,

Johan

        [Koninklijke Bibliotheek, National Library of the Netherlands]
        Prins Willem-Alexanderhof 5 | 2595 BE Den Haag
Postbus 90407 | 2509 LK Den Haag | (070) 314 09 11 | www.kb.nl<http://www.kb.nl/>
        [http://www.kb.nl/sites/default/files/dots.jpg]
        English version<http://www.kb.nl/en/email> | Disclaimer<http://www.kb.nl/disclaimer>

**Comment by stweil** [comment]
@bitsgalore @carlwilson : My pull request #74 fixes two problems and some warnings. I think that this issue can be closed.

Regards,
Stefan

**Comment by bitsgalore** [comment]
Patch by Stefan Weil fixes this  issue: <https://github.com/openpreserve/jpylyzer/pull/74>

Fixed in version 1.14.4
