### ISSUE TITLE
Recurse switch does't result in recursing for glob expressions under Linux 

### ISSUE THREAD

**Issue by bitsgalore** [openpreserve/jpylyzer#67]
Under Linux, running this command:

    jpylyzer -r ./jpylyzer-test-files/

Result: all files in directory and its subdirectories are analyzed.

Doing this:

   jpylyzer -r ./jpylyzer-test-files/*.jp2

Now matching files in subdirectories are not analyzed. Under Windows both commands work as expected.

**Comment by anjackson** [comment]
The shell is expanding the glob, so the command being run will passed the list of matching files.  This should do what you intend:

    jpylyzer -r "./jpylyzer-test-files/*.jp2"

However, TBH, I would not have had the same expectation as you, and would not consider the Linux behaviour to be buggy.

**Comment by bitsgalore** [comment]
You're right, I now remember I've seen this before, I had completely forgotten about that. Phew!

Thanks!
