### ISSUE TITLE
Compliance with PEP8 and PEP257

### ISSUE THREAD

**Issue by surfmikko** [openpreserve/jpylyzer#68]
## Dev Effort
1D

## Description
Python community has well established coding conventions. Coding according to these guidelines will help any Python programmer to contribute for the project. Also there are very good automated tools to check that coding style is consistent: pep8, pylint, autopep8 etc..

Python coding conventions are described at PEP8: https://www.python.org/dev/peps/pep-0008/

Documentation guidelines allow community supported tools like Sphinx to automatically generate HTML and PDF documentation.

Detailed documentation guidelines are described at PEP257: https://www.python.org/dev/peps/pep-0257/

**Comment by bitsgalore** [comment]
Thanks, I ran the latest version of the code through autopep8 (which I do periodically anyway) which is a start. A check with pep8 shows up some additional issues that need to be resolved manually. will have more in-depth look later; meanwhile I'll leave the issue open.

**Comment by bitsgalore** [comment]
Latest periodic PEP cleanup:  <https://github.com/openpreserve/jpylyzer/releases/tag/1.18.0b4> passes PEP8 with `--max-line-length=100`.
