### ISSUE TITLE
Mix-up of files/folders master branch and gh-pages

### ISSUE THREAD

**Issue by bitsgalore** [openpreserve/jpylyzer#78]
For some reason stuff from the master branch of jpylyzer ended up in the gh-pages branch and vice versa. E.g. see *jpylyzer* and *vagrant* dirs under <https://github.com/openpreserve/jpylyzer/tree/gh-pages>

Even stranger, these are all files that are meant to be blocked by gitignore!

**Comment by stweil** [comment]
What are those gh-pages for? To remove the commits on gh-pages, you can switch to that branch and use these commands:

    git reset --hard HEAD~3
    git push -f

Which commits are wrong in the master branch? Those should be reverted.

**Comment by stweil** [comment]
#79 and #80 should fix both branches.

**Comment by bitsgalore** [comment]
Thanks again!
