### ISSUE TITLE
Optional or supplementary MIX output

### ISSUE THREAD

**Issue by bbboru** [openpreserve/jpylyzer#85]
Not sure if this the best forum. I couldn't find a listserv or wiki.

It would a marvelous thing if the technical metadata could be rendered as valid MIX 2.0, either as a supplement nested within the output or as an alternative. Has there been any discussion of this?

http://www.loc.gov/standards/mix/

Best,
Brian Sheppard

**Comment by bitsgalore** [comment]
Hi Brian,

Actually this is something I briefly considered when I started the development of jpylyzer, but mapping JPEG 2000 properies to corresponding MIX elements isn't that straightforward. Some examples, from the top of my head (there are more):

* The JP2 spec allows the use of multiple Colour Specification boxes, which may contain conflicting information. So how should this be handled in MIX?
* JPEG 2000 has 2 different sets of fields for storing resolution info (Capture and Display resolution), which can have different values. Also here any mapping to MIX x/y samplingFrequency will be pretty arbitrary.

For users who need output in MIX format, I think this could be done most easily as post-processing using [XSLT transformations](https://en.wikipedia.org/wiki/XSLT). I don't have any experience with that myself, but if anyone is interested in writing some stylesheets, I'd be happy to include them in the jpylyzer distribution.
